// <auto-generated />
using System;
using ApiEtec.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEtec.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiEtec.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeEquipe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeEquipe = "Bastard"
                        },
                        new
                        {
                            Id = 2,
                            NomeEquipe = "Pxg"
                        });
                });

            modelBuilder.Entity("ApiEtec.Models.Jogador", b =>
                {
                    b.Property<int>("Rm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rm"));

                    b.Property<int?>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rm");

                    b.HasIndex("EquipeId");

                    b.ToTable("Jogadores");

                    b.HasData(
                        new
                        {
                            Rm = 1,
                            Nome = "Jogador Teste1",
                            Turma = "2º ano"
                        },
                        new
                        {
                            Rm = 2,
                            Nome = "Jogador Teste2",
                            Turma = "3º ano"
                        });
                });

            modelBuilder.Entity("ApiEtec.Models.Jogador", b =>
                {
                    b.HasOne("ApiEtec.Models.Equipe", "Equipe")
                        .WithMany("Jogadores")
                        .HasForeignKey("EquipeId");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ApiEtec.Models.Equipe", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
